#!/usr/bin/env ruby
require 'commander/import'
require 'bugguide'

program :name, 'BugGuide'
program :version, BugGuide::VERSION
program :description, 'Command-line tool for scraping data from https://bugguide.net'

command :checklist do |c|
  c.syntax = "bugguide checklist [taxon name]"
  c.option "-s", '--state STATE', String, '2-letter code of a US state or CA province'
  c.option "-c", '--county COUNTY', String, "US county, full name, e.g. Alameda, Middlesex."
  c.option "-f", '--format table|csv', String, "Output format"
  c.action do |args, opts|
    taxa = BugGuide::Taxon.search(args[0], state: opts.state)
    if taxa.size == 0
      abort "No matching taxa found"
    elsif taxa.size == 1
      taxon = taxa.first
    else
      puts "Multiple taxon results, choose one (hit ENTER to choose the first)"
      taxa.each_with_index do |taxon, i|
        say "[#{i}] #{taxon.common_name} (#{taxon.scientific_name}) https://bugguide.net/node/view/#{taxon.id}"
      end
      choice = ask "Choice: "
      taxon = taxa[choice.to_i]
      taxon = taxa.first if choice.blank?
    end
    abort "You must choose a taxon" if taxon.blank?
    
    # Instead of searching photos, just output the taxon info
    if opts.format == 'csv'
      puts ["TAXON ID", "NAME"].join(',')
      puts [taxon.id, taxon.scientific_name].join(',')
    else
      puts "Selected taxon:"
      puts "  ID: #{taxon.id}"
      puts "  Name: #{taxon.scientific_name}"
      puts "  URL: https://bugguide.net/node/view/#{taxon.id}"
    end
  end
end
